# Generated by Django 4.2.3 on 2023-07-28 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publicaciones', '0002_categoria_publicaciones_delete_publicacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicaciones',
            options={'ordering': ('-publicado',)},
        ),
        migrations.RenameField(
            model_name='publicaciones',
            old_name='texto',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='publicaciones',
            old_name='subtitulo',
            new_name='empresa',
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='colaborador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='categoria',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publicaciones.categoria'),
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='imagen',
            field=models.ImageField(blank=True, default='static/post_default.jpg', null=True, upload_to='media'),
        ),
    ]
